### PR TITLE
(maint) Updating the puppet agent compatibility

### PR DESCRIPTION
**Pull request by Ramesh7**
- https://github.com/puppetlabs/puppetlabs-facts/pull/59

### CODE REVIEW

**Review by gavindidrichsen — APPROVED** [review]

**Comment by donoghuc** [comment]
Why would we do a major version release for this. This is not needed and i think would cause some upgrade friction.

**Comment by Ramesh7** [comment]
> Why would we do a major version release for this. This is not needed and i think would cause some upgrade friction.

I am not sure what all conventions are followed for this module but with CAT modules whenever there is compatibility/support gets updated then we update the major version. 
Would like to know what should be the next version for this module based on conventions you guys are following, will update the same.

**Comment by donoghuc** [comment]
Were the other modules major versions updated due to ruby 3 compatibility? I guess major version bump does not add that much friction, i'm not sure if people are constraining modules to major version. Either way, there is no change to the module code at all so it does not make sense to me why we would do a major version bump.

**Comment by Ramesh7** [comment]
> Were the other modules major versions updated due to ruby 3 compatibility? I guess major version bump does not add that much friction, i'm not sure if people are constraining modules to major version. Either way, there is no change to the module code at all so it does not make sense to me why we would do a major version bump.

I have updated the version to 1.6.0, please review.

**Review by donoghuc — APPROVED** [review]

**Pull request merged**
